#cloud-config

users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFeepzHjD1YIqKVuU6/oDag6vXuiuGC0GW8LNrINrNBgh7mgImA7uyXpWtfGfjBQ1qTfswEtj4fgfwqlxMfkdX4pdc0sCdtks9UWU4wass8bWAZ/8yrM2SLddO/J9pIgE7a9ZlvfXohwnYIto6nLsoiFEONHUspS2n+0OGiPVrBlqprbwEAnNpba+s7gnHbeUtYJ+6NcPCqKPuZAzG3/Q6m5MrRnx0A0q3KwaivmHr35AerfuVMKlPj84RLvxOkQ2rMpOtih0qih7Fo3M5693YTntEwkTi4RWkJwc32tk6oiKXfaSej/4sud4VeznA9d/37UKwD2HAd1S9d+hHNuiJnyGDfOroaD1fFw/XNLHCq0iOoZTU6TRK3jKyTv/45HImtxjntMm3XbmXPbdrUbks6s6wOWokqcQSx/J0GDs6awNJO6ptKzNN4yLH48kLyU97qWsre+FudgoZTqW6jZH/UW1gMo9CAA2aLwon8UyPsLxbU6DuREl+WYQFUOBmO2k= ody@home
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtuQTrN4p6+ZGFW4Yq5wSlv0lxpfozjhhZG6chP/1fc5M8BYk6TNeucstwiztgxg+s13EXN77EvEBMkJGQinQ5QsIjn2IzSYz5yz5+EdqUKRs0aPqAcmO53EsElJQ7FVAVrAUXRLlSwymkbW++qDxn06JqGb0mSrvQhPKlI2pE89m4zgaQcvJkb/JGwLm1AZBZ4eJ/NReYrth1pzXM1EmRV8KX7b2+/lbgLE4/cbiyuOsHzBhbZxmYio7Fu++jlLqbtP7MhH2NTUgZ6s21nKIvbRuVontKmWsN8c2C4yPosTNv8q8FWsp3p7OaPzrJx7eDU0B9tY+kHcFQ/pTCInyY6YxyGn4s/GYE5CEAd8CVMJs/PaAPCoqXl3EXiYjJulIbBmpJj8Q/EBdNafBFzNk8PMAO+aMWdttA2fKCBYSMBm+oe+hOylcxfqANklA+Cyw0p/jHFnFDX+SPWeZOSBmyLbF1qRe0RCbSKED1aOXEmcad0zcNm0dYvml877FbY1s= root@home
